---
- hosts: all
  become: true

  roles:
    - geerlingguy.repo-epel

  tasks:
  - name: Add server to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: '10.0.0.10	auth.example.org auth'
      state: present

  - name: Add client to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: '10.0.0.100	somebox.example.org somebox'
      state: present

  - name: Install LDAP client
    package:
      name: openldap-clients
      state: present


- hosts: auth
  become: true
  tasks:
  - name: Install openldap server
    package:
      name: openldap-servers
      state: present

  - name: Start LDAP service
    service:
      name: slapd
      state: started
      enabled: true

  - name: Install Python LDAP support
    package:
      name: python-ldap
      state: present

  - name: Configure LDAP base
    ldap_attr:
      dn: olcDatabase={2}hdb,cn=config
      name: olcSuffix
      values: "dc=example,dc=org"
      state: exact

  - name: Configure LDAP RootDN
    ldap_attr:
      dn: olcDatabase={2}hdb,cn=config
      name: olcRootDN
      values: "cn=admin,dc=example,dc=org"
      state: exact

  - name: Configure LDAP RootDN password
    ldap_attr:
      dn: olcDatabase={2}hdb,cn=config
      name: olcRootPW
      values: "{SSHA}0TtWtaWnyCNw59LLdzAauF8+drxl2olj"
      state: exact

  # May not be the best thing, but since we're configuring with Ansible
  # without this, you'd have to provide auth (base dn/pw) in all of the
  # ldap_entry addition
  # https://serverfault.com/questions/490624/why-cant-i-create-my-first-object-in-my-open-ldap-server
  - name: Allow domain socket write access to LDAP tree
    ldap_attr:
      dn: olcDatabase={2}hdb,cn=config
      name: olcAccess
      values:
      - >-
        {0}to *
         by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" write
         by * read
      state: exact

  - name: Create top of LDAP tree
    ldap_entry:
      dn: dc=example,dc=org
      objectClass:
        - dcObject
        - organization
      attributes:
        o: example
        dc: example

  - name: Create OU for users
    ldap_entry:
      dn: ou=users,dc=example,dc=org
      objectClass: organizationalUnit

  - name: Create OU for groups
    ldap_entry:
      dn: ou=groups,dc=example,dc=org
      objectClass: organizationalUnit
