---
- hosts: all
  become: true

  roles:
    - geerlingguy.repo-epel

  tasks:
  - name: Add server to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: '10.0.0.10	auth.example.org auth'
      state: present

  - name: Add client to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: '10.0.0.100	somebox.example.org somebox'
      state: present


- hosts: auth
  become: true
  tasks:
  - name: Install openldap server
    package:
      name: openldap-servers
      state: present

  - name: Start LDAP service
    service:
      name: slapd
      state: started
      enabled: true
